### ISSUE TITLE
Nice Color Scheme, its shame that i made it

### ISSUE THREAD

**Issue by Eric-Bwr** [knimix/CLion-Settings#1]
Could have at least given Credit. Sad to see how you evolved. I had some hope in you. But no, saying this is the best Color Scheme and so on... I feel sorry for you. It doesnt just look exacly like mine, it is the one i gave you. It has the Color Scheme copy in the name :)

**Comment by konradx64** [comment]
fixed

**Comment by Eric-Bwr** [comment]
Superb
